server:
    port: 0

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
    instance:
        instanceId: ${spring.application.name}:${random.int} 
        hostname: localhost